txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
files=getSampleFiles()
print(files)
promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
peak <- readPeakFile(files[[6]])
peak
tagMatrix <- tagMatrixList[[6]]
peakAnno <- annotatePeak(files[[6]], tssRegion=c(-3000, 3000),TxDb=txdb,annoDb="org.Hs.eg.db")
test=as.data.frame(peakAnno)
write.table(test,"Peak_Annotation.txt",row.names=F,sep="\t")
jpeg("covplot.jpeg")
covplot(peak, weightCol="V5")
dev.off()
jpeg("tagHeatmap.jpeg")
tagHeatmap(tagMatrix, xlim=c(-3000, 3000), color="red")
dev.off()
jpeg("peakHeatmap.jpeg")
peakHeatmap(files[[6]], TxDb=txdb, upstream=3000, downstream=3000, color="red")
dev.off()
jpeg("plotAvgProf2.jpeg")
plotAvgProf2(files[[6]], TxDb=txdb, upstream=3000, downstream=3000,xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
dev.off()
jpeg("plotAnnoPie.jpeg")
plotAnnoPie(peakAnno)
dev.off()
jpeg("upsetplot.jpeg",width = 720)
upsetplot(peakAnno, vennpie=TRUE)
dev.off()